version: '3.8'
services:
  products:
    build: 
      context: ./products
      dockerfile: Dockerfile
    ports:
      - '81:8081'
    volumes:
      - ./products:/app
      - /app/node_modules
  cart:
    build: 
      context: ./cart
      dockerfile: Dockerfile
    ports:
      - '82:8082'
    volumes:
      - ./cart:/app
      - /app/node_modules
  
  container:
    build:
      context: ./container
      dockerfile: Dockerfile
    ports:
      - '80:8080'
    volumes:
      - ./container:/app
      - /app/node_modules
    depends_on:
      - products
      - cart
  
  npm:
    image: node:14
    working_dir: /app
    entrypoint: ['npm']
    volumes:
      - ./products:/app

  # backend:
  #   build: ./backend
  #   # build:
  #   #   context: ./backend
  #   #   dockerfile: Dockerfile
  #   #   args:
  #   #     some-arg: 1
  #   ports:
  #     - '80:80'
  #   volumes:
  #     - logs:/app/logs
  #     - ./backend:/app
  #     - /app/node_modules
  #   env_file:
  #     - ./env/backend.env
  #   depends_on:
  #     - mongodb
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - ./frontend/src:/app/src
  #   stdin_open: true
  #   tty: true
  #   depends_on:
  #     - backend